site_name: PromG Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
  - PromG Documentation: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Modules:
      - Database Manager: db-management.md
      - Data Importer: data-importer.md
  - explanation.md
