site_name: PromG Documentation

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select

plugins:
  - search
  - mkdocstrings

nav:
  - PromG Documentation: index.md
  - getting-started.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Modules:
      - Database Manager: module-db-management.md
      - Data Importer: module-data-importer.md
      - Database Manager: module:db-management.md
      - Data Importer: module-data-importer.md
      - Transformer: module-transformer.md
      - Exporter: module-exporter.md
      - Inference Engine: module-inference_engine.md
      - Process Model Discovery: module-process_discovery.md
      - Task Identification: module-task_identification.md
  - related_publications.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences