# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Bump Version

on: workflow_call
jobs:
  bump-version:
    name: Bump Version 🤜
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Grab current_version
      run: echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
    - shell: bash
      run: |
        set -x
        pip install --no-cache-dir bump2version
         ~/.local/bin/bumpversion --allow-dirty --no-tag --no-commit --current-version ${{ env.current_version }} patch version.md
    - name: Read bumped version
      run: echo "grep '# version' version.md | cut -d ' ' -f3"
