# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on: 
  workflow_call:
    inputs:
        should-read-source-from-artifacts:
          description: 'If true, the source code to build is read from an artifact instead of checked out from the repo'
          default: false
          required: false
          type: boolean
jobs:
  build:
    name: Build Python 🐍 distributions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest source code
      uses: actions/checkout@v3 # We either checkout the latest source code
      if: ! inputs.should-read-source-from-artifacts
    - name: Download sources from artifact # Or we download the source code as artifact
      if: inputs.should-read-source-from-artifacts
      uses: actions/download-artifact@v3
      with:
        name: source
        path: source
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python3 -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
