# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python 🐍 distributions 📦 to PyPI

on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  set-up-python:
    uses: ./.github/workflows/call-python-setup.yml
  bump-version:
    uses: ./.github/workflows/call-python-bumpversion.yml
    needs: set-up-python
    with:
      artifact-name-source-directory: "version-file" # Store adjusted source code in this artifact
  build-python-distribution:
    uses: ./.github/workflows/call-python-build.yml
    needs: bump-version
    with:
      read-source-from-artifacts: true
      source-directory: "source" # Read source code with bumped version from this artifact
  build-n-publish:
    name: Build, bump and publish Python 🐍 distributions 📦 to PyPI
    needs: build-python-distribution
    runs-on: ubuntu-latest
    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
