# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python 🐍 distributions 📦 to PyPI

on: 
  push:
    branches:
      - master
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: bump2version-action
    - name: current_version
      run: echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
  # You may pin to the exact commit or the version.
  # uses: FragileTech/bump-version@c022e89bf1b6c4753bd39bc1f9c979da7fabe2f8
    - name: Bump Version
      uses: FragileTech/bump-version@v1.0.4
      with:
        # Version of the project *before* the bump.
        current_version: "${{ env.current_version }}"
        # List of files in which to bump the version. The format is a concatenation of paths separated by a whitespace character.
        files: version.md
        # Name of the identity that is used in the commit's author signature.
        commit_name: VersionBumpBot
        # Email of the identity that is used in the commit's author signature.
        commit_email: ava.swevels@gmail.com
        # GitHub personal access token of the identity. `bump-version` uses it together with `login` to push to the repository.
        token: "${{ secrets.BOT_TOKEN }}"
    - name: Build a binary wheel and a source tarball
      run: >-
        python3 -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
