# This workflow will build a Python Package using Twine when a feature is pushed
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Feature

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Build Python 🐍 distributions
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: Ava-S/promg-core/.github/workflows/call-python-setup.yml@main
    - name: Build Python 🐍 distributions
      uses: Ava-S/promg-core/.github/workflows/call-python-build.yml@main
