# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python 🐍 distributions 📦 to PyPI

on: 
  push:
    branches:
      - main
jobs:
  set-up-python:
    uses: Ava-S/promg-core/.github/workflows/call-python-setup.yml@main
  bump-version:
    uses: Ava-S/promg-core/.github/workflows/call-python-bumpversion.yml@main
    needs: set-up-python
  build-python-distribution:
    uses: Ava-S/promg-core/.github/workflows/call-python-build.yml@main
    needs: bump-version
  build-n-publish:
    name: Build, bump and publish Python 🐍 distributions 📦 to PyPI
    needs: build-python-distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dist artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
