# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python 🐍 distributions 📦 to PyPI

on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  set-up-python:
    uses: ./.github/workflows/call-python-setup.yml
  bump-version:
    uses: ./.github/workflows/call-python-bumpversion.yml
    needs: set-up-python
    with:
      artifact-name-version-file: "version-file" # Store adjusted version file in this artifact
  build-python-distribution:
    uses: ./.github/workflows/call-python-build.yml
    needs: bump-version
    with:
      read-version-from-artifacts: true
      artifact-name-version-file: "version-file" # Read version file with bumped version from this artifact
  publish-artifact:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    needs: build-python-distribution
    runs-on: ubuntu-latest
    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
  push-updated-version-to-git:
    name: Push the changed version number to git
    runs-on: ubuntu-latest
    needs: publish-artifact
    steps:
      - name: Checkout latest source code
        uses: actions/checkout@v3
      - name: Download version file from artifact # Download the adjust version file
        uses: actions/download-artifact@v3
        with:
          name: "version-file"
      - name: Find updated version number
        run: echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
      - name: Update branch with new version number
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'version.md'
          author_name: Ava Swevels
          author_email: ava.swevels@gmail.com
          commit: --signoff
          default_author: github_actor
          message: 'Bump version number to ${{ env.current_version }} (from workflow)'
          pathspec_error_handling: exitImmediately
          push: true
          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          tag: '${{ env.current_version }} --force'
          # Arguments for the git push --tags command (any additional argument will be added after --tags)
          # Default: ''
          # tag_push: '--force'
